version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Check code formatting
          command: npm run prettier
      - run:
          name: Lint code
          command: npm run lint
      - run:
          name: Check types
          command: npm run check-types
      - run:
          name: Test code
          command: npm test
      - run:
          name: Build
          command: npm run build
      - run:
          name: Build demo
          command: npm run build-demo
      - run:
          name: Report coverage
          command: bash <(curl -s https://codecov.io/bash)
